### ISSUE TITLE
Create MWE of hardware documentation

### ISSUE THREAD

**Issue by lochhh** [SainsburyWellcomeCentre/aeon_docs#14]
Begin with feeder, with drawings by @lorycalca

**Comment by lochhh** [comment]
We have 3 versions:
* Initial [vertical list with Hopper, IR sensor in separate subsections](https://lochhh.github.io/aeon_docs/reference/hardware/feeder.html#assembly-instructions)
* [Hopper, IR sensor in different tabs](https://lochhh.github.io/aeon_docs/reference/hardware/feeder_tab.html#assembly-instructions) - the downside is we don't have the navigation for each tab on the right
* [Hopper, IR sensor in separate subsections, with separate images for each tab](https://lochhh.github.io/aeon_docs/reference/hardware/feeder_carousel.html#assembly-instructions) - we may want to move the buttons to the top of the carousel to keep these in the same place when the text instructions differ in length, or when images with different aspect ratios are used. If we decide to keep the buttons on top, @lorycalca may want to leave some blank space at the top of each image to accommodate these buttons (see [here](https://sphinx-carousel.readthedocs.io/en/latest/extended_features.html#:~:text=com/fWyn9A2l.jpg-,Buttons%20on%20Top,-%EF%83%81) for an example).

**Comment by Dario55** [comment]
Thank you. Some combination of the above will generate what we discussed yesterday, I think.
From the solution two, the tabs and the list on the right are good, but  pressing next should take to the next tab, not the next item in the list on the left.
Within each tab things should be organize similarly to the page at this link (https://sphinx-carousel.readthedocs.io/en/latest/extended_features.html#:~:text=com/fWyn9A2l.jpg-,Buttons%20on%20Top,-%EF%83%81).
. So that you have the image of step one and below the description of step one. 

For lory: when you generate the new images, it might be that the strokes needs to be a bit thicker, because lines look very faint on my screen. 

Please let me know if anything is unclear.

**Comment by lorycalca** [comment]
We have generated the first two steps of each Feeder hopper and IR sensor.


 
![Feeder_components](https://github.com/SainsburyWellcomeCentre/aeon_docs/assets/29209983/c604e664-3847-4eb5-ae29-6308bf2a2b15)
![sensor-step1](https://github.com/SainsburyWellcomeCentre/aeon_docs/assets/29209983/c688b7ce-da60-430f-b5f8-e05fc252d053)
![sensor-step2](https://github.com/SainsburyWellcomeCentre/aeon_docs/assets/29209983/3d2a9fd5-4af3-4a3e-9865-2fa0f089756e)
![step1](https://github.com/SainsburyWellcomeCentre/aeon_docs/assets/29209983/2bb766f1-8386-4c75-bb7e-9f0cd7ddfbd3)
![step2](https://github.com/SainsburyWellcomeCentre/aeon_docs/assets/29209983/af2be24b-cc4a-443d-bb64-2d9b9652ce32)

**Comment by lochhh** [comment]
Notes:
- Carousel images:  
  - 16:9 aspect ratio (e.g. 1920 x 1080 pixels), 
  - margins: 15% top (to accommodate controls), min 3% bottom

**Comment by Dario55** [comment]
We will keep this in mind, but ATM this is not the solution we are adopting right?

**Comment by Dario55** [comment]
@lochhh  Any update on this?

**Comment by lochhh** [comment]
[4th version with carousel within each tab](https://lochhh.github.io/aeon_docs/reference/hardware/feeder_carousel_in_tab.html#assembly-guide)

> Pressing next should take to the next tab or the next item in the list on the right, not the next item in the list on the left. 
The convention (e.g. [1](https://numpy.org/doc/stable/dev/gitwash/development_setup.html), [2](https://open-ephys.github.io/shuttledrive-docs/pages/assemblyjig.html)) is that the previous and next buttons allow one to navigate to different pages, not subsections within a page (this is what the right side bar is intended for). We can hide these buttons if they add to confusion.  

> The list on the right should contain, as subcategories of assembly instructions, the various tabs. 
This is not straightforward to achieve as it most likely requires custom template and JavaScript. What do you think about this [dropdown option](https://lochhh.github.io/aeon_docs/reference/hardware/feeder.html#assembly-guide) ?

**Comment by lochhh** [comment]
Update dropdown is [here](https://lochhh.github.io/aeon_docs/reference/hardware/feeder.html#assembly-guide).

**Comment by Dario55** [comment]
Very nice :) :) :)
