### ISSUE TITLE
Update hardware module assembly guide

### ISSUE THREAD

**Issue by lochhh** [SainsburyWellcomeCentre/aeon_docs#29]
- [ ] Remove step-by-step panels. These can be links to downloadable PDFs for now. 

- [ ] Include list of harp devices connected to the respective device with link to the harp website

- [ ] Include part list (e.g., ballberig, beambrake etc).

- [ ] Include slider motor
- [ ] add example wiring diagram

**Comment by lorycalca** [comment]
I have the following 4 guidelines in Dropbox: Feeder, Nest, Arena, Commutator.
Drawings are basically ready but missing the final step by step written part. 
Must double check the extent of the details required and add what is needed.
Clarification on Harp and part list needed.

**Comment by NeuroThom** [comment]
Harp device system on AEON

| Harp Device                       | Associated Component            | AEON Rig	| Description                                                   | Quantity | Link                                                                                                       |
|-----------------------------------|---------------------------------|-------------|---------------------------------------------------------------|----------|---------------------------------------------------------------------------------------------|
| **Harp Output Expander**          | Foraging Patches (Feeders)      |             | Expander module to connect feeder to harp system. 1 per patch | 4        | [Harp Output Expander](https://harp-tech.org/api/Harp.OutputExpander.html)                  |
| **Harp CameraController Gen2**    | Cameras                         |             | Controller to trigger all cameras in the arena                | 1        | [Harp CameraController Gen2](https://harp-tech.org/api/Harp.CameraControllerGen2.html)      |
| **Harp Timestamp Generator Gen3** | Arena (Synchronizes all devices)|             | Synchronizes all harp devices in the arena                    | 1        | [Harp Timestamp Generator Gen3](https://harp-tech.org/api/Harp.TimestampGeneratorGen3.html) |
| **Harp Micropython device**       | Ephys linear rail drive         |             | Linear rail position controller and position sensor reciever  | 1        | [Micropython Harp device](https://github.com/SainsburyWellcomeCentre/microharp)             |
| **Harp SoundCard**                | SP speaker                      |             | Control and monitoring of spatial speaker                     | 1        | [Micropython Harp device](https://github.com/SainsburyWellcomeCentre/microharp)             |
