### ISSUE TITLE
Update layout of homepage

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_docs#3]
The homepage should be geared towards people who want a general overview of the project. Then separate tab(s) should be for Users & Contributors (links from this page(s) would contain info on Development Practices, Data Contract, the `Note` callout on the current 'update-docs' branch index, etc.).

One possibility for the homepage tabs could be:

- one tab for each aeon_repo
- one tab called "Users & Contributors"

**Comment by lochhh** [comment]
**Home**
* short description of the project
* link to "Getting started" (target audience: everyone)
* link to "User guide" 
* link to "Contributor's guide" 

**Getting started** (goal: decide if the Aeon platform is for you)
* Overview of the project - what, why, who of Aeon
* Aeon fundamentals
  * Hardware components (e.g., mechatronics)
  * Software components (e.g., data acquisition, architecture, analysis)

**User guide**
* Tutorials (learning-oriented, to acquire basic competence, practical steps)
* How-to guides (task/problem-oriented, assumes competency, practical steps; e.g., how to install feeder, how to analyse position data)

**Contributor's guide**
* General development guidelines, workflows 
* Language-specific guidelines (e.g., _style guidelines_ for developing in C#, Python...)
* Tutorials (learning-oriented, to acquire basic competence, practical steps; e.g., setting up dev environment, running tests, building docs)
* How-to guides (task/problem-oriented, assumes competency, practical steps; e.g., how to contribute docs, how to add a new Device)

**Reference** (information-oriented, theoretical knowledge)
* API reference 
* Glossary

**About**
* design considerations (explanation - understanding-oriented, theoretical knowledge)
* goals
* code of conduct
* project maintainers
