### ISSUE TITLE
Decide figures to include on the landing page

### ISSUE THREAD

**Issue by glopesdev** [SainsburyWellcomeCentre/aeon_docs#30]
To motivate and introduce the project it would be nice to include some figures describing the novel platform for natural behaviours, the modular structure of the arena and which kinds of experiments can be run. This would go before the section breakdown in the site langing page.

**Comment by lochhh** [comment]
Preview available at https://lochhh.github.io/aeon_docs/

**Comment by lochhh** [comment]
Feedback from @Dario55 
> Hey some comments here:
> 
> Overall it looks already very good. I prefer the version in the first page. I have a couple of small comments to make more explicit some of the core feature like multianimal tracking, 24/7 aspect and long term recording. (This is all specific to sfn version of the website and can be changed).
>  
> 1)The arena we are kind of showing in in the page header already, so next to Learn more I would put the logo with the 24/7 and all the behaviour. THis would make visually explicit the 24/7 component of the project.
> 2)For the wording of the learn more section I would edit slighly:  Find out more about how the platform allows us to record and quantify different natural behaviours, such as foraging, nesting escape and social interaction, and their neural basis, continuously over multiple weeks
> 3). I wonder if we can add two fields already here called "Multianimal tracking" and "Long-term Neuropixels recording" or somenthing like that, that will take you to a page with a brief description of how that is done and the links to the relevant part of the website. 
> 4)We could also have one like that for 24/7, and in that case I would keep the current image for the learn more and use the 24/7 logo there 

> I am wondering if it would be good to have this image somewhere in the front page too,  maybe instead of the [24/7] one in 1 
> <img width="289" alt="landing-digging" src="https://github.com/user-attachments/assets/675a9df2-fa67-42cb-88ad-612de320e3aa">

**Comment by lochhh** [comment]
@Dario55 I think the first "Learn more about Aeon" description covers "multi-animal tracking" and "long-term npx recording". What I've done here is when you click on "To the introduction" it'll send you the "Getting started" page - this now has two cards, one for multi-animal tracking, another for npx recording. Wdyt?

**Comment by Dario55** [comment]
Yes I think that looks good. The only suggestion if possible would be to have also a figure inside the cards describing the content. That could be just for now and we remove in the final website. it is just to make it more catchy. For multianimal tracking could be some simplified version of the box in the top right corner of section 3 of the poster. for the neuropixels maybe the schematics in the probe location box in section 4 of the poster overlayed to the rasterplot or a zoom in of the raw voltage traces.
